version: 1
disable_existing_loggers: false

formatters:
  default:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  access:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stdout
  file:
    formatter: default
    class: logging.FileHandler
    filename: /app/backend/app_performance.log
    mode: a

loggers:
  "":
    level: INFO
    handlers: [default, file]
    propagate: false
  uvicorn:
    level: INFO
    handlers: [default, file]
    propagate: false
  uvicorn.error:
    level: INFO
    handlers: [default, file]
    propagate: false
  uvicorn.access:
    level: INFO
    handlers: [default, file]
    propagate: false
